#!/usr/bin/env python3
"""
pack_terrain.py - pack the ClearVieques geodata into one browser-loadable script.

Reads (for each site id `caracas`, `mosquito`):
    data/<site>_near.i16, data/<site>_far.i16   raw Int16 little-endian, centimetres above mean sea level,
                                                row-major, row 0 = northernmost, column 0 = westernmost
    data/<site>.json                            site metadata written by tools/build_terrain.py
    data/osm_<site>.json                        sparse OSM features in local metres (optional)
and writes
    data/terrain.js

    window.CV_TERRAIN = {
      caracas:  { meta:{...}, near:{nx,nz,dx,dz,x0,z0,b64:"..."}, far:{nx,nz,dx,dz,x0,z0,b64:"..."}, osm:{...} },
      mosquito: { ... }
    };

Site frame:  x = east (m), z = SOUTH (m; north is -z), y = elevation above mean sea level (m).
Cell (row j, col i) is centred at  x = x0 + (i + 0.5) dx,  z = z0 + (j + 0.5) dz ;  elevation_m = int16[j*nx + i] / 100.

Decoding in the browser (little-endian hosts, i.e. every WebGPU-capable machine):
    const bytes = Uint8Array.from(atob(g.b64), c => c.charCodeAt(0));
    const cm    = new Int16Array(bytes.buffer);          // centimetres
    const elev  = (i, j) => cm[j * g.nx + i] / 100;      // metres above MSL (negative = below sea level)

Standard library only (json, base64, argparse).  Usage:
    python3 tools/pack_terrain.py [--data-dir data] [--out data/terrain.js] [--sites caracas mosquito]
"""
from __future__ import annotations

import argparse
import base64
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE_IDS = ("caracas", "mosquito")


def load_grid(data: Path, site: str, kind: str, spec: dict) -> dict:
    """Read one .i16 file, verify its size against the grid spec, and return the js-side grid record."""
    path = data / f"{site}_{kind}.i16"
    raw = path.read_bytes()
    nx, nz = int(spec["nx"]), int(spec["nz"])
    if len(raw) != nx * nz * 2:
        sys.exit(f"{path}: {len(raw)} bytes, expected {nx * nz * 2} for {nx}x{nz} Int16")
    # value sanity: little-endian int16 in centimetres, clamped to +-327 m
    vals = struct.unpack("<" + "h" * min(len(raw) // 2, 4096), raw[:8192])
    if max(abs(v) for v in vals) > 32700:
        sys.exit(f"{path}: values outside +-327.00 m - wrong endianness or units?")
    rec = {"nx": nx, "nz": nz, "dx": spec["dx"], "dz": spec["dz"], "x0": spec["x0"], "z0": spec["z0"],
           "b64": base64.b64encode(raw).decode("ascii")}
    assert base64.b64decode(rec["b64"]) == raw
    return rec


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-dir", default=str(ROOT / "data"))
    ap.add_argument("--out", default=None, help="default: <data-dir>/terrain.js")
    ap.add_argument("--sites", nargs="+", default=list(SITE_IDS))
    args = ap.parse_args()
    data = Path(args.data_dir)
    out = Path(args.out) if args.out else data / "terrain.js"

    sites = {}
    for sid in args.sites:
        meta_path = data / f"{sid}.json"
        if not meta_path.exists():
            sys.exit(f"missing {meta_path} - run tools/build_terrain.py first")
        meta = json.loads(meta_path.read_text())
        osm_path = data / f"osm_{sid}.json"
        osm = json.loads(osm_path.read_text()) if osm_path.exists() else None
        sites[sid] = {
            "meta": meta,
            "near": load_grid(data, sid, "near", meta["grids"]["near"]),
            "far": load_grid(data, sid, "far", meta["grids"]["far"]),
            "osm": osm,
        }
        print(f"{sid}: near {meta['grids']['near']['nx']}x{meta['grids']['near']['nz']}, "
              f"far {meta['grids']['far']['nx']}x{meta['grids']['far']['nz']}, osm={'yes' if osm else 'no'}")

    header = (
        "/* ClearVieques terrain - GENERATED by tools/pack_terrain.py from data/*.i16, data/<site>.json, data/osm_<site>.json. Do not edit.\n"
        " * Frame: x east (m), z SOUTH (m; north = -z), elevation above MSL (m). Grids are row-major, row 0 = northernmost.\n"
        " * Cell (row j, col i) centre: x = x0+(i+0.5)dx, z = z0+(j+0.5)dz.  b64 = base64 of raw Int16 little-endian centimetres:\n"
        " *   const bytes = Uint8Array.from(atob(g.b64), c => c.charCodeAt(0)); const cm = new Int16Array(bytes.buffer); elev_m = cm[j*g.nx+i]/100;\n"
        " * Data: NOAA NCEI CUDEM 1/9 arc-second (public domain, not for navigation); OSM features (c) OpenStreetMap contributors, ODbL. */\n"
    )
    body = "window.CV_TERRAIN = " + json.dumps(sites, separators=(",", ":"), ensure_ascii=True) + ";\n"
    out.write_text(header + body)
    print(f"wrote {out} ({out.stat().st_size / 1e6:.2f} MB)")


if __name__ == "__main__":
    main()
